import { Golfer, GolferBucket } from '@/types/database';

// === GOLFERS FROM MASTERS 2026 FIELD ===
// Top 12 (Bucket 1: Pick 2)
const top12: Golfer[] = [
  { id: 1, name: 'Scottie Scheffler', world_rank: 1, bucket: 'top12', live_score: -8, thru_hole: 18, today_score: -3, status: 'active' },
  { id: 2, name: 'Jon Rahm', world_rank: 2, bucket: 'top12', live_score: -5, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 3, name: 'Bryson DeChambeau', world_rank: 3, bucket: 'top12', live_score: -10, thru_hole: 18, today_score: -6, status: 'active' },
  { id: 4, name: 'Rory McIlroy', world_rank: 4, bucket: 'top12', live_score: -6, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 5, name: 'Ludvig Åberg', world_rank: 5, bucket: 'top12', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 6, name: 'Xander Schauffele', world_rank: 6, bucket: 'top12', live_score: -7, thru_hole: 18, today_score: -4, status: 'active' },
  { id: 7, name: 'Cameron Young', world_rank: 7, bucket: 'top12', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 8, name: 'Matt Fitzpatrick', world_rank: 8, bucket: 'top12', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 9, name: 'Tommy Fleetwood', world_rank: 9, bucket: 'top12', live_score: -3, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 10, name: 'Robert MacIntyre', world_rank: 10, bucket: 'top12', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 11, name: 'Collin Morikawa', world_rank: 11, bucket: 'top12', live_score: -1, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 12, name: 'Justin Rose', world_rank: 12, bucket: 'top12', live_score: 2, thru_hole: 18, today_score: 4, status: 'cut' },
];

// Mid bucket (13-50, Pick 3)
const midGolfers: Golfer[] = [
  { id: 13, name: 'Patrick Reed', world_rank: 13, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 14, name: 'Hideki Matsuyama', world_rank: 14, bucket: 'mid', live_score: -7, thru_hole: 18, today_score: -4, status: 'active' },
  { id: 15, name: 'Min Woo Lee', world_rank: 15, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 16, name: 'Jordan Spieth', world_rank: 16, bucket: 'mid', live_score: -5, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 17, name: 'Brooks Koepka', world_rank: 17, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 18, name: 'Chris Gotterup', world_rank: 18, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 19, name: 'Viktor Hovland', world_rank: 19, bucket: 'mid', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 20, name: 'Shane Lowry', world_rank: 20, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 21, name: 'Si Woo Kim', world_rank: 21, bucket: 'mid', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 22, name: 'Russell Henley', world_rank: 22, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 23, name: 'Akshay Bhatia', world_rank: 23, bucket: 'mid', live_score: -6, thru_hole: 18, today_score: -3, status: 'active' },
  { id: 24, name: 'Jacob Bridgeman', world_rank: 24, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 25, name: 'Patrick Cantlay', world_rank: 25, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 26, name: 'Nicolai Højgaard', world_rank: 26, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 27, name: 'Jake Knapp', world_rank: 27, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 28, name: 'Tyrrell Hatton', world_rank: 28, bucket: 'mid', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 29, name: 'Sepp Straka', world_rank: 29, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 30, name: 'J.J. Spaun', world_rank: 30, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 31, name: 'Justin Thomas', world_rank: 31, bucket: 'mid', live_score: -5, thru_hole: 18, today_score: -3, status: 'active' },
  { id: 32, name: 'Adam Scott', world_rank: 32, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 33, name: 'Corey Conners', world_rank: 33, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 34, name: 'Marco Penge', world_rank: 34, bucket: 'mid', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 35, name: 'Cameron Smith', world_rank: 35, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 36, name: 'Jason Day', world_rank: 36, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 37, name: 'Maverick McNealy', world_rank: 37, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 38, name: 'Sungjae Im', world_rank: 38, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 39, name: 'Gary Woodland', world_rank: 39, bucket: 'mid', live_score: 2, thru_hole: 18, today_score: 3, status: 'active' },
  { id: 40, name: 'Sam Burns', world_rank: 40, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 41, name: 'Harris English', world_rank: 41, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 42, name: 'Max Homa', world_rank: 42, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 43, name: 'Brian Harman', world_rank: 43, bucket: 'mid', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 44, name: 'Daniel Berger', world_rank: 44, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 45, name: 'Rasmus Højgaard', world_rank: 45, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 46, name: 'Aaron Rai', world_rank: 46, bucket: 'mid', live_score: -3, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 47, name: 'Kurt Kitayama', world_rank: 47, bucket: 'mid', live_score: 1, thru_hole: 18, today_score: 2, status: 'cut' },
  { id: 48, name: 'Ben Griffin', world_rank: 48, bucket: 'mid', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 49, name: 'Ryan Fox', world_rank: 49, bucket: 'mid', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 50, name: 'Casey Jarvis', world_rank: 50, bucket: 'mid', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
];

// Wildcard bucket (51+, Pick 2)
const wildcardGolfers: Golfer[] = [
  { id: 51, name: 'Keegan Bradley', world_rank: 51, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 52, name: 'Dustin Johnson', world_rank: 52, bucket: 'wildcard', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 53, name: 'Harry Hall', world_rank: 53, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 54, name: 'Alex Noren', world_rank: 54, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 55, name: 'Ryan Gerard', world_rank: 55, bucket: 'wildcard', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 56, name: 'Michael Kim', world_rank: 56, bucket: 'wildcard', live_score: -3, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 57, name: 'Nick Taylor', world_rank: 57, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 58, name: 'Sam Stevens', world_rank: 58, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 59, name: 'Wyndham Clark', world_rank: 59, bucket: 'wildcard', live_score: -4, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 60, name: 'Haotong Li', world_rank: 60, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 61, name: 'Carlos Ortiz', world_rank: 61, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 62, name: 'Sami Välimäki', world_rank: 62, bucket: 'wildcard', live_score: 2, thru_hole: 18, today_score: 3, status: 'cut' },
  { id: 63, name: 'Max Greyserman', world_rank: 63, bucket: 'wildcard', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 64, name: 'Sergio García', world_rank: 64, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 65, name: 'Aldrich Potgieter', world_rank: 65, bucket: 'wildcard', live_score: -3, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 66, name: 'Rasmus Neergaard-Petersen', world_rank: 66, bucket: 'wildcard', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 67, name: 'Nico Echavarria', world_rank: 67, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 68, name: 'Andrew Novak', world_rank: 68, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 69, name: 'Matt McCarty', world_rank: 69, bucket: 'wildcard', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 70, name: 'Tom McKibbin', world_rank: 70, bucket: 'wildcard', live_score: -5, thru_hole: 18, today_score: -3, status: 'active' },
  { id: 71, name: 'Michael Brennan', world_rank: 71, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 72, name: 'Kristoffer Reitan', world_rank: 72, bucket: 'wildcard', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 73, name: 'Johnny Keefer', world_rank: 73, bucket: 'wildcard', live_score: 3, thru_hole: 18, today_score: 4, status: 'cut' },
  { id: 74, name: 'Bubba Watson', world_rank: 74, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 75, name: 'Charl Schwartzel', world_rank: 75, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 76, name: 'Zach Johnson', world_rank: 76, bucket: 'wildcard', live_score: 2, thru_hole: 18, today_score: 3, status: 'active' },
  { id: 77, name: 'Davis Riley', world_rank: 77, bucket: 'wildcard', live_score: -2, thru_hole: 18, today_score: -1, status: 'active' },
  { id: 78, name: 'Fifa Laopakdee', world_rank: 78, bucket: 'wildcard', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 79, name: 'Naoyuki Kataoka', world_rank: 79, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 80, name: 'Danny Willett', world_rank: 80, bucket: 'wildcard', live_score: -3, thru_hole: 18, today_score: -2, status: 'active' },
  { id: 81, name: 'Ethan Fang', world_rank: 81, bucket: 'wildcard', live_score: 2, thru_hole: 18, today_score: 3, status: 'active' },
  { id: 82, name: 'José María Olazábal', world_rank: 82, bucket: 'wildcard', live_score: 4, thru_hole: 18, today_score: 5, status: 'cut' },
  { id: 83, name: 'Brandon Holtz', world_rank: 83, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 84, name: 'Mateo Pulcini', world_rank: 84, bucket: 'wildcard', live_score: 1, thru_hole: 18, today_score: 2, status: 'active' },
  { id: 85, name: 'Mason Howell', world_rank: 85, bucket: 'wildcard', live_score: -1, thru_hole: 18, today_score: 0, status: 'active' },
  { id: 86, name: 'Jackson Herrington', world_rank: 86, bucket: 'wildcard', live_score: 0, thru_hole: 18, today_score: 1, status: 'active' },
  { id: 87, name: 'Brian Campbell', world_rank: 87, bucket: 'wildcard', live_score: 3, thru_hole: 18, today_score: 4, status: 'cut' },
  { id: 88, name: 'Vijay Singh', world_rank: 88, bucket: 'wildcard', live_score: 5, thru_hole: 18, today_score: 6, status: 'cut' },
  { id: 89, name: 'Ángel Cabrera', world_rank: 89, bucket: 'wildcard', live_score: 2, thru_hole: 18, today_score: 3, status: 'active' },
  { id: 90, name: 'Mike Weir', world_rank: 90, bucket: 'wildcard', live_score: 4, thru_hole: 18, today_score: 5, status: 'cut' },
  { id: 91, name: 'Fred Couples', world_rank: 91, bucket: 'wildcard', live_score: 3, thru_hole: 18, today_score: 4, status: 'cut' },
];

export const allGolfers: Golfer[] = [...top12, ...midGolfers, ...wildcardGolfers];

export function getGolfersByBucket(bucket: GolferBucket): Golfer[] {
  return allGolfers.filter(g => g.bucket === bucket);
}
